"""add chunk table

Revision ID: 08a95a832340
Revises: c96bd23576a3
Create Date: 2026-04-08 16:56:09.451213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a95a832340'
down_revision: Union[str, Sequence[str], None] = 'c96bd23576a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_profile_snapshot_user_id_key'), 'user_profile_snapshot', type_='unique')
    op.drop_index(op.f('ix_user_profile_snapshot_user_id'), table_name='user_profile_snapshot')
    op.create_index(op.f('ix_user_profile_snapshot_user_id'), 'user_profile_snapshot', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_snapshot_user_id'), table_name='user_profile_snapshot')
    op.create_index(op.f('ix_user_profile_snapshot_user_id'), 'user_profile_snapshot', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_profile_snapshot_user_id_key'), 'user_profile_snapshot', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
