"""add chunk table

Revision ID: 971acdcdd25c
Revises: 08a95a832340
Create Date: 2026-04-08 16:59:37.225077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel 
import pgvector

# revision identifiers, used by Alembic.
revision: str = '971acdcdd25c'
down_revision: Union[str, Sequence[str], None] = '08a95a832340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    # ### end Alembic commands ###
